import 'package:cloud_firestore/cloud_firestore.dart';

/// Message types
enum MessageType {
  text,
  image,
  file,
  hireRequest,
  system,
}

/// Chat message model
class MessageModel {
  final String id;
  final String chatId;
  final String senderId;
  final String senderName;
  final String? senderImage;
  final MessageType type;
  final String? text;
  final String? imageUrl;
  final String? fileName;
  final String? fileUrl;
  final Map<String, dynamic>? metadata; // For hire requests, system messages, etc.
  final DateTime timestamp;
  final Map<String, bool> readBy; // {userId: true}
  final bool isEdited;
  final DateTime? editedAt;

  MessageModel({
    required this.id,
    required this.chatId,
    required this.senderId,
    required this.senderName,
    this.senderImage,
    required this.type,
    this.text,
    this.imageUrl,
    this.fileName,
    this.fileUrl,
    this.metadata,
    required this.timestamp,
    required this.readBy,
    this.isEdited = false,
    this.editedAt,
  });

  factory MessageModel.fromMap(String id, Map<String, dynamic> map) {
    return MessageModel(
      id: id,
      chatId: map['chatId'],
      senderId: map['senderId'],
      senderName: map['senderName'],
      senderImage: map['senderImage'],
      type: MessageType.values.firstWhere(
        (e) => e.toString() == 'MessageType.${map['type']}',
        orElse: () => MessageType.text,
      ),
      text: map['text'],
      imageUrl: map['imageUrl'],
      fileName: map['fileName'],
      fileUrl: map['fileUrl'],
      metadata: map['metadata'] != null
          ? Map<String, dynamic>.from(map['metadata'])
          : null,
      timestamp: (map['timestamp'] as Timestamp).toDate(),
      readBy: Map<String, bool>.from(map['readBy'] ?? {}),
      isEdited: map['isEdited'] ?? false,
      editedAt: map['editedAt'] != null
          ? (map['editedAt'] as Timestamp).toDate()
          : null,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'chatId': chatId,
      'senderId': senderId,
      'senderName': senderName,
      'senderImage': senderImage,
      'type': type.toString().split('.').last,
      'text': text,
      'imageUrl': imageUrl,
      'fileName': fileName,
      'fileUrl': fileUrl,
      'metadata': metadata,
      'timestamp': Timestamp.fromDate(timestamp),
      'readBy': readBy,
      'isEdited': isEdited,
      'editedAt': editedAt != null ? Timestamp.fromDate(editedAt!) : null,
    };
  }

  /// Check if message is read by a specific user
  bool isReadBy(String userId) {
    return readBy[userId] ?? false;
  }

  /// Create a text message
  factory MessageModel.text({
    required String chatId,
    required String senderId,
    required String senderName,
    String? senderImage,
    required String text,
  }) {
    return MessageModel(
      id: '', // Will be generated by Firestore
      chatId: chatId,
      senderId: senderId,
      senderName: senderName,
      senderImage: senderImage,
      type: MessageType.text,
      text: text,
      timestamp: DateTime.now(),
      readBy: {senderId: true}, // Sender has already read it
    );
  }

  /// Create an image message
  factory MessageModel.image({
    required String chatId,
    required String senderId,
    required String senderName,
    String? senderImage,
    required String imageUrl,
    String? caption,
  }) {
    return MessageModel(
      id: '',
      chatId: chatId,
      senderId: senderId,
      senderName: senderName,
      senderImage: senderImage,
      type: MessageType.image,
      imageUrl: imageUrl,
      text: caption,
      timestamp: DateTime.now(),
      readBy: {senderId: true},
    );
  }

  /// Create a file message
  factory MessageModel.file({
    required String chatId,
    required String senderId,
    required String senderName,
    String? senderImage,
    required String fileName,
    required String fileUrl,
  }) {
    return MessageModel(
      id: '',
      chatId: chatId,
      senderId: senderId,
      senderName: senderName,
      senderImage: senderImage,
      type: MessageType.file,
      fileName: fileName,
      fileUrl: fileUrl,
      timestamp: DateTime.now(),
      readBy: {senderId: true},
    );
  }

  /// Create a hire request message
  factory MessageModel.hireRequest({
    required String chatId,
    required String senderId,
    required String senderName,
    String? senderImage,
    required String bookingId,
    required Map<String, dynamic> bookingDetails,
  }) {
    return MessageModel(
      id: '',
      chatId: chatId,
      senderId: senderId,
      senderName: senderName,
      senderImage: senderImage,
      type: MessageType.hireRequest,
      text: 'Sent a hire request',
      metadata: {
        'bookingId': bookingId,
        'bookingDetails': bookingDetails,
      },
      timestamp: DateTime.now(),
      readBy: {senderId: true},
    );
  }

  /// Create a system message
  factory MessageModel.system({
    required String chatId,
    required String text,
    Map<String, dynamic>? metadata,
  }) {
    return MessageModel(
      id: '',
      chatId: chatId,
      senderId: 'system',
      senderName: 'System',
      type: MessageType.system,
      text: text,
      metadata: metadata,
      timestamp: DateTime.now(),
      readBy: {},
    );
  }

  MessageModel copyWith({
    Map<String, bool>? readBy,
    bool? isEdited,
    DateTime? editedAt,
    String? text,
  }) {
    return MessageModel(
      id: id,
      chatId: chatId,
      senderId: senderId,
      senderName: senderName,
      senderImage: senderImage,
      type: type,
      text: text ?? this.text,
      imageUrl: imageUrl,
      fileName: fileName,
      fileUrl: fileUrl,
      metadata: metadata,
      timestamp: timestamp,
      readBy: readBy ?? this.readBy,
      isEdited: isEdited ?? this.isEdited,
      editedAt: editedAt ?? this.editedAt,
    );
  }
}
